# Generated by Django 4.2.3 on 2023-07-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='need_init_at',
            field=models.DateField(default='9999-01-01'),
        ),
    ]
