# Generated by Django 4.2.3 on 2023-07-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_need_init_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished_at',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='postponed_at',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_at',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_at',
            field=models.DateField(blank=True),
        ),
    ]
