# Generated by Django 4.2.3 on 2023-07-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_finished_at_alter_task_postponed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='etapas',
            field=models.CharField(choices=[('não iniciada', 'não iniciada'), ('iniciada', 'iniciada'), ('finalizada', 'finalizada'), ('justificada', 'justificada')], default='não iniciada', max_length=13),
        ),
        migrations.AlterField(
            model_name='task',
            name='need_init_at',
            field=models.DateField(default='01/01/2023'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('atrasada', 'Atrasada'), ('no dia', 'No Dia'), ('futura', 'Futura')], max_length=13),
        ),
    ]
