# Generated by Django 4.2.3 on 2023-07-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_etapas_alter_task_need_init_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('atrasada', 'Atrasada'), ('no dia', 'No Dia'), ('futura', 'Futura')], max_length=20),
        ),
    ]
