# Generated by Django 4.2.3 on 2023-07-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_etapas_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='nome_pessoa',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='etapas',
            field=models.CharField(choices=[('não iniciada', 'não iniciada'), ('iniciada', 'iniciada'), ('finalizada', 'finalizada'), ('justificada', 'justificada')], default='não iniciada', max_length=20),
        ),
    ]
